Repository jackdwayne/arrhythmia_project, pull requests merged in 2021-04, with the labels that each got.

#46 Add initial backend documentation
  backend/README.md
  backend/mainapp/README.md
  backend/patientdb/README.md
  frontend/package-lock.json
  frontend/src/components/Chart2.js
  frontend/src/components/DefaultDisplay.js
Labels: documentation

#45 file upload now working for multiple files, then triggering script to…
  backend/mainapp/settings.py
  backend/patRecFormatter.py
  backend/patientdb/migrations/0001_initial.py
  backend/patientdb/migrations/0002_auto_20210223_2118.py
  backend/patientdb/migrations/0003_auto_20210223_2127.py
  backend/patientdb/migrations/0004_auto_20210223_2130.py
  backend/patientdb/migrations/0005_auto_20210223_2132.py
  backend/patientdb/migrations/0006_auto_20210318_2011.py
  backend/patientdb/migrations/0007_auto_20210318_2014.py
  backend/patientdb/migrations/0008_auto_20210318_2055.py
  backend/patientdb/models.py
  backend/patientdb/serializers.py
  backend/patientdb/urls.py
  backend/patientdb/views.py
  backend/temp_uploaded_patient_data/100.atr
  backend/temp_uploaded_patient_data/100.dat
  backend/temp_uploaded_patient_data/100.hea
  backend/temp_uploaded_patient_data/100.xws
  frontend/package-lock.json
  frontend/src/components/DefaultDisplay.js
  frontend/src/components/Users.js
  frontend/yarn.lock
Labels: enhancement

#47 File input
  backend/README.md
  backend/mainapp/README.md
  backend/mainapp/settings.py
  backend/patRecFormatter.py
  backend/patientdb/README.md
  backend/patientdb/migrations/0001_initial.py
  backend/patientdb/migrations/0002_auto_20210223_2118.py
  backend/patientdb/migrations/0003_auto_20210223_2127.py
  backend/patientdb/migrations/0004_auto_20210223_2130.py
  backend/patientdb/migrations/0005_auto_20210223_2132.py
  backend/patientdb/migrations/0006_auto_20210318_2011.py
  backend/patientdb/migrations/0007_auto_20210318_2014.py
  backend/patientdb/migrations/0008_auto_20210318_2055.py
  backend/patientdb/models.py
  backend/patientdb/serializers.py
  backend/patientdb/urls.py
  backend/patientdb/views.py
  backend/temp_uploaded_patient_data/100.atr
  backend/temp_uploaded_patient_data/100.dat
  backend/temp_uploaded_patient_data/100.hea
  backend/temp_uploaded_patient_data/100.xws
  frontend/package-lock.json
  frontend/src/components/DefaultDisplay.js
  frontend/src/components/Users.js
  frontend/yarn.lock
Labels: enhancement, milestone

#48 Frontend Now Has Dynamic Patient Queries
  backend/.gitignore
  backend/README.md
  backend/mainapp/README.md
  backend/mainapp/settings.py
  backend/patRecFormatter.py
  backend/patientdb/README.md
  backend/patientdb/migrations/0001_initial.py
  backend/patientdb/migrations/0002_auto_20210223_2118.py
  backend/patientdb/migrations/0003_auto_20210223_2127.py
  backend/patientdb/migrations/0004_auto_20210223_2130.py
  backend/patientdb/migrations/0005_auto_20210223_2132.py
  backend/patientdb/migrations/0006_auto_20210318_2011.py
  backend/patientdb/migrations/0007_auto_20210318_2014.py
  backend/patientdb/migrations/0008_auto_20210318_2055.py
  backend/patientdb/migrations/0009_auto_20210408_1926.py
  backend/patientdb/migrations/__init__.py
  backend/patientdb/models.py
  backend/patientdb/serializers.py
  backend/patientdb/urls.py
  backend/patientdb/views.py
  backend/temp_uploaded_patient_data/100.atr
  backend/temp_uploaded_patient_data/100.dat
  backend/temp_uploaded_patient_data/100.hea
  backend/temp_uploaded_patient_data/100.xws
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/AllPatients.js
  frontend/src/components/Chart2.js
  frontend/src/components/DefaultDisplay.js
  frontend/src/components/Patient.js
  frontend/src/components/Users.js
  frontend/src/graphql-logic/queries.js
  frontend/src/index.js
  frontend/yarn.lock
Labels: enhancement, milestone

#52 Insertion Working Properly
  backend/mainapp/settings.py
  backend/patRecFormatter.py
  backend/patientdb/views.py
  backend/temp_uploaded_patient_data/100.atr
  backend/temp_uploaded_patient_data/100.dat
  backend/temp_uploaded_patient_data/100.hea
  backend/temp_uploaded_patient_data/100.xws
  frontend/src/components/Users.js
Labels: bug, enhancement

#58 Frontend Annotation Update
  backend/patientdb/views.py
  frontend/src/App.js
  frontend/src/components/Chart2.js
  frontend/src/components/DefaultDisplay.js
  frontend/src/components/Users.js
  frontend/src/graphql-logic/queries.js
Labels: bug, enhancement, milestone

#64 Update README.md
  README.md
Labels: documentation

#65 Additional Documentation for Machine Learning Models and Django Models
  backend/README.md
  backend/patientdb/Arrythmias ERD Diagram.pdf
  backend/patientdb/README.md
Labels: documentation
